spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ---
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

    show-sql: true
application :
  constants:
    master-code-number: 7
    student-code-number: 7
#server:
#  port: 8083